[package]
name = "url_shortener"
version = "0.1.0"
authors = ["trivelle"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.1.1"
fastrand = "1.4.1"
rusqlite = "0.25.3"